CNV-Site/CNV-Site/Controllers/FondosComunesInversionController.cs
using CNV_Site.Models;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CNV_Site.Controllers
{
    public class FondosComunesInversionController : Controller
    {
        //
        // GET: /FondosComunesInversion/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var client = new RestClient();
            var request = new RestRequest();
            client = new RestClient(ConfigurationManager.AppSettings["UrlAPI"]);
            IRestResponse response;
            ListaUltimaColocacionesInstrumentos Lfci = new ListaUltimaColocacionesInstrumentos();
            ListaUltimaColocacionesInstrumentos LfciA = new ListaUltimaColocacionesInstrumentos();
            List<DocUltimaColocacionesInstrumentos> dfci = new List<DocUltimaColocacionesInstrumentos>();
            ListaSociedadesGerentes Lsg = new ListaSociedadesGerentes();
            ListaSociedadesGerentes Lti = new ListaSociedadesGerentes();
            ListaSociedadesGerentes Lsd = new ListaSociedadesGerentes();

            ViewModelFondoComunesInversion vmFCI = new ViewModelFondoComunesInversion();
            Lfci.data = new List<UltimaColocacionesInstrumentos>();
            LfciA.data = new List<UltimaColocacionesInstrumentos>(); 
            Lsg.data =  new List<SociedadesGerentes>();
            Lti.data = new List<SociedadesGerentes>();
            Lsd.data = new List<SociedadesGerentes>();

            request = new RestRequest("/Instrumentos/FCI/BuscaFondosComunes?tipoId=1&limit=3", Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lfci = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaUltimaColocacionesInstrumentos>(response.Content);
            request = new RestRequest("/Instrumentos/FCI/BuscaFondosComunes?tipoId=2&limit=3", Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                LfciA = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaUltimaColocacionesInstrumentos>(response.Content);

            request = new RestRequest("/Instrumentos/FCI/ListaSociedadesGerentes/", Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lsg = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaSociedadesGerentes>(response.Content);

            request = new RestRequest("/Instrumentos/FCI/ListaTiposInversion/", Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lti = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaSociedadesGerentes>(response.Content);

            request = new RestRequest("/Instrumentos/FCI/ListaSociedadesDepositarias/", Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lsd = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaSociedadesGerentes>(response.Content);



            vmFCI.LUCIC = Lfci;
            vmFCI.LUCIA = LfciA;
            vmFCI.Lsg = Lsg;
            vmFCI.Lti = Lti;
            vmFCI.Lsd = Lsd;

            return View(vmFCI);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Busqueda(FormCollection data)
        {
            var client = new RestClient();
            var request = new RestRequest();
            client = new RestClient(ConfigurationManager.AppSettings["UrlAPI"]);
            IRestResponse response;
            ListaUltimaColocacionesInstrumentos Lfci = new ListaUltimaColocacionesInstrumentos();
            ListaUltimaColocacionesInstrumentos LfciA = new ListaUltimaColocacionesInstrumentos();
            List<DocUltimaColocacionesInstrumentos> dfci = new List<DocUltimaColocacionesInstrumentos>();
            ListaSociedadesGerentes Lsg = new ListaSociedadesGerentes();
            ListaSociedadesGerentes Lti = new ListaSociedadesGerentes();
            ListaSociedadesGerentes Lsd = new ListaSociedadesGerentes();
            string sg = "", ti = "", sd = "",tp="";
            tp = data["tipo"] == "" ? "" : "&tipoId=" + data["tipo"];
            sg = data["Lsg"]==""?"": "&idSocGerente="+data["Lsg"];
            sd = data["Lsd"] == "" ? "" : "&codSociedadDepositaria=" + data["Lsd"];
            ti = data["Lti"] == "" ? "" : "&idTipoInversion=" + data["Lti"];
            ViewModelFondoComunesInversion vmFCI = new ViewModelFondoComunesInversion();
            Lfci.data = new List<UltimaColocacionesInstrumentos>();
            LfciA.data = new List<UltimaColocacionesInstrumentos>();
            Lsg.data = new List<SociedadesGerentes>();
            Lti.data = new List<SociedadesGerentes>();
            Lsd.data = new List<SociedadesGerentes>();
            string q = sg + sd + ti+ tp; 
            request = new RestRequest("/Instrumentos/FCI/BuscaFondosComunes?desde=" + DateTime.Today.AddMonths(-12).ToShortDateString() + q, Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lfci = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaUltimaColocacionesInstrumentos>(response.Content);
            Session.Add("filtrosfci", q);
            Session.Timeout = 180;


            request = new RestRequest("/Instrumentos/FCI/ListaSociedadesGerentes/", Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lsg = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaSociedadesGerentes>(response.Content);

            request = new RestRequest("/Instrumentos/FCI/ListaTiposInversion/", Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lti = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaSociedadesGerentes>(response.Content);

            request = new RestRequest("/Instrumentos/FCI/ListaSociedadesDepositarias/", Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lsd = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaSociedadesGerentes>(response.Content);



            vmFCI.LUCIC = Lfci;
           // vmFCI.LUCIA = LfciA;
            vmFCI.Lsg = Lsg;
            vmFCI.Lti = Lti;
            vmFCI.Lsd = Lsd;

            return View(vmFCI);
        }
        [AllowAnonymous]
        public ActionResult Busqueda(int pagina = 1)
        {
            var client = new RestClient();
            var request = new RestRequest();
            client = new RestClient(ConfigurationManager.AppSettings["UrlAPI"]);
            IRestResponse response;
            string filtros = "";
            ListaUltimaColocacionesInstrumentos Lfci = new ListaUltimaColocacionesInstrumentos();
            ListaUltimaColocacionesInstrumentos LfciA = new ListaUltimaColocacionesInstrumentos();
            List<DocUltimaColocacionesInstrumentos> dfci = new List<DocUltimaColocacionesInstrumentos>();
            ListaSociedadesGerentes Lsg = new ListaSociedadesGerentes();
            ListaSociedadesGerentes Lti = new ListaSociedadesGerentes();
            ListaSociedadesGerentes Lsd = new ListaSociedadesGerentes();
            ViewModelFondoComunesInversion vmFCI = new ViewModelFondoComunesInversion();
            Lfci.data = new List<UltimaColocacionesInstrumentos>();
            LfciA.data = new List<UltimaColocacionesInstrumentos>();
            Lsg.data = new List<SociedadesGerentes>();
            Lti.data = new List<SociedadesGerentes>();
            Lsd.data = new List<SociedadesGerentes>();
            filtros = Session["filtrosfci"].ToString();
            pagina=pagina.ToString() == "1" ? 1 : (pagina - 1);
            request = new RestRequest("/Instrumentos/FCI/BuscaFondosComunes?desde=" + DateTime.Today.AddMonths(-12).ToShortDateString() + filtros + "&skip=" + pagina * 100, Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lfci = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaUltimaColocacionesInstrumentos>(response.Content);

            request = new RestRequest("/Instrumentos/FCI/ListaSociedadesGerentes/", Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lsg = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaSociedadesGerentes>(response.Content);

            request = new RestRequest("/Instrumentos/FCI/ListaTiposInversion/", Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lti = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaSociedadesGerentes>(response.Content);

            request = new RestRequest("/Instrumentos/FCI/ListaSociedadesDepositarias/", Method.GET);
            response = client.Execute(request);
            if (response.StatusCode != System.Net.HttpStatusCode.NotFound)
                Lsd = Newtonsoft.Json.JsonConvert.DeserializeObject<ListaSociedadesGerentes>(response.Content);



            vmFCI.LUCIC = Lfci;
            // vmFCI.LUCIA = LfciA;
            vmFCI.Lsg = Lsg;
            vmFCI.Lti = Lti;
            vmFCI.Lsd = Lsd;

            return View(vmFCI);

           
        }
    }
}

CNV-Site/CNV-Site/Views/FondosComunesInversion/Busqueda.cshtml
@model CNV_Site.Models.ViewModelFondoComunesInversion

@{
    ViewBag.Title = "Fondos Comunes de Inversion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link type="text/css" href="~/Content/assets/css/fondos-comunes-inversion.css" rel="stylesheet">
<style>
    .ui-autocomplete-loading {
        background: white url("/Content/assets/img/ui-anim_basic_16x16.gif") right center no-repeat;
    }
</style>
<link rel="stylesheet" href="~/AdminLTE/plugins/jquery-ui/jquery-ui.css">


<section id="title-int" class="fondos-comunes-inversion">
    <div class="container-fluid no-padding">
        <h1>Fondos Comunes de Inversión</h1>
        <p>Es un instrumento de inversión mediante el cual un grupo de personas con similares objetivos de inversión aporta su dinero para que un profesional lo administre, invirtiendo en una cartera diversificada de activos.</p>
    </div>
</section>
<section>
    <div class="container-fluid bg-busqueda">
        <div class="container">
            <h1>Buscador de Fondos Comunes de Inversión</h1>

            <div class="col-lg-8 col-lg-offset-2">
                @using (Html.BeginForm("Busqueda", "FondosComunesInversion", FormMethod.Post, new { name = "FondoComunesInversionBuscar", id = "FondoComunesInversionBuscar", enctype = "multipart/form-data" }))
                {
                    <p>Mostrar:</p>
                    <div class="form-group">

                        <select class="form-control" id="tipo" name="tipo">
                            <option value="">Todos</option>
                            <option value="2">Abiertos</option>
                            <option value="1">Cerrados</option>

                        </select> <div class="select_arrow"> </div>
                    </div>
                    <div class="form-group">

                        <select id="tipoBFF" class="form-control">
                            <option value="0">Seleccione el Tipo de Busqueda</option>
                            <option value="1">por Tipo de Inversión</option>
                            <option value="2">por Sociedad Gerente</option>
                            <option value="3">por Sociedad Depositaria</option>
                        </select> <div class="select_arrow"> </div>
                    </div>

                    <p>Criterios de búsqueda:</p>
                    <div id="Lti" class="form-group hidden">
                        @Html.DropDownListFor(model => model.Lti, new SelectList(Model.Lti.data.AsEnumerable(), "idSocGerente", "denominacion"), "por Tipo de Inversión", new { @class = "form-control" })


                        <div class="select_arrow"> </div>
                    </div>
                    <div id="Lsg" class="form-group hidden">
                        @Html.DropDownListFor(model => model.Lsg, new SelectList(Model.Lsg.data.AsEnumerable(), "idSocGerente", "denominacion"), "por Sociedad Gerente", new { @class = "form-control" })


                        <div class="select_arrow"> </div>
                    </div>
                    <div id="Lsd" class="form-group hidden">
                        @Html.DropDownListFor(model => model.Lsd, new SelectList(Model.Lsd.data.AsEnumerable(), "idSocGerente", "denominacion"), "por Sociedad Depositaria", new { @class = "form-control" })


                        <div class="se lect_arrow"> </div>
                    </div>
                    <button id="btnFFBuscar" class="btn-blue hidden">BUSCAR</button>
                }
            </div>

        </div>
    </div>
</section>
<script>

    jQuery("#tipoBFF").on('change', function () {
        var opt = jQuery('#tipoBFF').val();
        if (opt == 1) {
            jQuery('#Lti').removeClass("hidden");
            jQuery('#Lsd').removeClass("hidden").addClass("hidden");
            jQuery('#Lsg').removeClass("hidden").addClass("hidden");


        }
        if (opt == 2) {
            jQuery('#Lsg').removeClass("hidden");
            jQuery('#Lsd').removeClass("hidden").addClass("hidden");
            jQuery('#Lti').removeClass("hidden").addClass("hidden");

        }
        if (opt == 3) {
            jQuery('#Lsd').removeClass("hidden");
            jQuery('#Lsg').removeClass("hidden").addClass("hidden");
            jQuery('#Lti').removeClass("hidden").addClass("hidden");

        }
        jQuery('#btnFFBuscar').removeClass("hidden");
    });

</script>

<section id="content">
    <div class="container-fluid bg-fondos-comunes-inversion">
        <div class="container">
            <h1>Resultados de la Busqueda</h1>
            <div id="exTab1" class="container">
               
                <div class="tab-content clearfix">
                    <div class="tab-pane active" id="1a">
                        <div class="table-responsive">
                            <div class="icon-scroll"><img src="~/Content/assets/img/horizontal-scroll.png"></div>
                            <table class="">
                                <thead>
                                    <tr>
                                        <th>Fecha de Lanzamiento</th>
                                        <th>DENOMINACIÓN</th>
                                        <th>
                                            OBJETO DE
                                            INVERSIÓN
                                        </th>
                                        <th>
                                            SOCIEDAD
                                            GERENTE
                                        </th>

                                        <th>
                                            SOCIEDAD
                                            DEPOSITARIA
                                        </th>
                                        <th>PROSPECTO</th>
                                        <th>REGLAMENTO DE GESTIÓN</th>
                                        <th>
                                            AVISO DE
                                            SUSCRIPCIÓN
                                        </th>
                                        <th>RESULTADO DE COLOCACIÓN</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (CNV_Site.Models.UltimaColocacionesInstrumentos fci in Model.LUCIC.data)
                                    {
                                        <tr>
                                            <td>
                                                @fci.fechaLanzamiento.ToString("d MMM yyyy",
            System.Globalization.CultureInfo.CreateSpecificCulture("es-AR"))
                                        </td>
                                        <td>@fci.denominacion</td>
                                        <td>@fci.tipo</td>
                                        <td>
                                            @fci.sociedadDepositaria
                                    </td>
                                    <td>
                                        @fci.sociedadGerente
                                    </td>
                                    <td><a href="#"><img src="~/Content/assets/img/pdf.png"></a></td>
                                    <td><a href="#"><img src="~/Content/assets/img/pdf.png"></a></td>
                                    <td><a href="#"><img src="~/Content/assets/img/pdf.png"></a></td>
                                    <td><a href="#"><img src="~/Content/assets/img/pdf.png"></a></td>
                                </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                            <div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite">Mostrando registros del @Model.LUCIC.desde al @Model.LUCIC.hasta de un total de @Model.LUCIC.totalElementos registros</div>
                        </div>
                        <div class="col-sm-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate" style="text-align: right;">
                                <ul class="pagination" style="margin-top: 5px;">
                                    <li class="paginate_button previous" id="DataTables_Table_0_previous">
                                        <a href="#" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0">Anterior</a>
                                    </li>
                                    @{ int rr = @Model.LUCIC.totalElementos % 100 > 0 ? (@Model.LUCIC.totalElementos / 100) + 1 : @Model.LUCIC.totalElementos / 100;}
                                    @for (int i = 1; i <= rr; i++)
                                    {
                                        <li class="paginate_button">
                                            <a href="@Url.Action("Busqueda", "FondosComunesInversion", new { pagina = i })" aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0">@i</a>
                                        </li>
                                    }

                                    <li class="paginate_button next" id="DataTables_Table_0_next">
                                        <a href="#" aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0">Siguiente</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <a href="@Url.Action("Index", "FondosComunesInversion")" class="btn-celeste center-btn	">REALIZAR NUEVA BÚSQUEDA</a>

                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript" src="~/Content/assets/js/hechos-relevantes.js"></script>

@Html.Partial("_Nav_int_Institucional")
<script type="text/javascript" src="~/Content/assets/js/main.js"></script>
<script>

    jQuery(document).ready(function () {
        var scrollPos = jQuery("#exTab1").offset().top;

        jQuery(window).scrollTop(scrollPos);
    });

</script>

CNV-Site/CNV-Site/Views/FondosComunesInversion/Index.cshtml
@model CNV_Site.Models.ViewModelFondoComunesInversion

@{
    ViewBag.Title = "Fondos Comunes de Inversion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link type="text/css" href="~/Content/assets/css/fondos-comunes-inversion.css" rel="stylesheet">
<style>
    .ui-autocomplete-loading {
        background: white url("/Content/assets/img/ui-anim_basic_16x16.gif") right center no-repeat;
    }
</style>
<link rel="stylesheet" href="~/AdminLTE/plugins/jquery-ui/jquery-ui.css">


<section id="title-int" class="fondos-comunes-inversion">
    <div class="container-fluid no-padding">
        <h1>Fondos Comunes de Inversión</h1>
        <p>Es un instrumento de inversión mediante el cual un grupo de personas con similares objetivos de inversión aporta su dinero para que un profesional lo administre, invirtiendo en una cartera diversificada de activos.</p>
    </div>
</section>
<section id="content">
    <div class="container-fluid bg-fondos-comunes-inversion">
        <div class="container">
            <h1>Últimas Colocaciones</h1>
            <div id="exTab1" class="container">
                <ul class="nav nav-pills">
                    <li class="active"> <a href="#1a" data-toggle="tab">FCI CERRADOS</a> </li>
                    <li><a href="#2a" data-toggle="tab">FCI ABIERTOS</a> </li>
                </ul>
                <div class="tab-content clearfix">
                    <div class="tab-pane active" id="1a">
                        <div class="table-responsive">
                            <div class="icon-scroll"><img src="~/Content/assets/img/horizontal-scroll.png"></div>
                            <table class="">
                                <thead>
                                    <tr>
                                        <th>Fecha de Lanzamiento</th>
                                        <th>DENOMINACIÓN</th>
                                        <th>
                                            OBJETO DE
                                            INVERSIÓN
                                        </th>
                                        <th>
                                            SOCIEDAD
                                            GERENTE
                                        </th>

                                        <th>
                                            SOCIEDAD
                                            DEPOSITARIA
                                        </th>
                                        <th>PROSPECTO</th>
                                        <th>REGLAMENTO DE GESTIÓN</th>
                                        <th>
                                            AVISO DE
                                            SUSCRIPCIÓN
                                        </th>
                                        <th>RESULTADO DE COLOCACIÓN</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach (CNV_Site.Models.UltimaColocacionesInstrumentos fci in Model.LUCIC.data)
                                {
                                    <tr>
                                        <td>@fci.fechaLanzamiento.ToString("d MMM yyyy",
            System.Globalization.CultureInfo.CreateSpecificCulture("es-AR"))</td>
                                        <td>@fci.denominacion</td>
                                        <td>@fci.tipo</td>
                                        <td>@fci.sociedadDepositaria
                                        </td>
                                        <td>
                                            @fci.sociedadGerente
                                        </td>
                                        <td><a href="#"><img src="~/Content/assets/img/pdf.png"></a></td>
                                        <td><a href="#"><img src="~/Content/assets/img/pdf.png"></a></td>
                                        <td><a href="#"><img src="~/Content/assets/img/pdf.png"></a></td>
                                        <td><a href="#"><img src="~/Content/assets/img/pdf.png"></a></td>
                                    </tr>
                                   }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane" id="2a">
                        <div class="table-responsive">
                            <table class="">
                                <thead>
                                    <tr>
                                        <th>Fecha de Lanzamiento</th>
                                        <th>DENOMINACIÓN</th>
                                        <th>OBJETO DE INVERSIÓN / TIPO DE RENTA</th>
                                        <th>
                                            SOCIEDAD
                                            GERENTE
                                        </th>

                                        <th>
                                            SOCIEDAD
                                            DEPOSITARIA
                                        </th>
                                        <th>PROSPECTO</th>
                                        <th>REGLAMENTO DE GESTIÓN</th>

                                        <th>RESULTADO DE COLOCACIÓN</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (CNV_Site.Models.UltimaColocacionesInstrumentos fci in Model.LUCIA.data)
                                    {
                                        <tr>
                                            <td>@fci.fechaLanzamiento.ToString("d MMM yyyy",
            System.Globalization.CultureInfo.CreateSpecificCulture("es-AR"))</td>
                                            <td>@fci.denominacion</td>
                                            <td>@fci.tipo</td>
                                            <td>
                                                @fci.sociedadDepositaria
                                        </td>
                                        <td>
                                            @fci.sociedadGerente
                                        </td>
                                        <td><a href="#"><img src="~/Content/assets/img/pdf.png"></a></td>
                                        <td><a href="#"><img src="~/Content/assets/img/pdf.png"></a></td>
                                        <td><a href="#"><img src="~/Content/assets/img/pdf.png"></a></td>
                                    </tr>
                                    }
                                   
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <a href="#" class="btn-blue-full">VER MES COMPLETO</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container-fluid bg-busqueda">
        <div class="container">
            <h1>Buscador de Fondos Comunes de Inversión</h1>

            <div class="col-lg-8 col-lg-offset-2">
              @using (Html.BeginForm("Busqueda", "FondosComunesInversion", FormMethod.Post, new {  name = "FondoComunesInversionBuscar", id = "FondoComunesInversionBuscar", enctype = "multipart/form-data" }))
              {
                    <p>Mostrar:</p>
                    <div class="form-group">

                        <select class="form-control" id="tipo" name="tipo">
                            <option value="">Todos</option>
                            <option value="2">Abiertos</option>
                            <option value="1">Cerrados</option>

                        </select> <div class="select_arrow"> </div>
                    </div>
                    <div class="form-group">

                        <select id="tipoBFF" class="form-control">
                            <option value="0">Seleccione el Tipo de Busqueda</option>
                            <option value="1">por Tipo de Inversión</option>
                            <option value="2">por Sociedad Gerente</option>
                            <option value="3">por Sociedad Depositaria</option>
                        </select> <div class="select_arrow"> </div>
                    </div>

                    <p>Criterios de búsqueda:</p>
                    <div id="Lti" class="form-group hidden" >
                        @Html.DropDownListFor(model => model.Lti, new SelectList(Model.Lti.data.AsEnumerable(), "idSocGerente", "denominacion"), "por Tipo de Inversión",new { @class= "form-control" })


                       <div class="select_arrow"> </div>
                    </div>
                <div id="Lsg" class="form-group hidden">
                              @Html.DropDownListFor(model => model.Lsg, new SelectList(Model.Lsg.data.AsEnumerable(), "idSocGerente", "denominacion"), "por Sociedad Gerente", new { @class = "form-control" })


                        <div class="select_arrow"> </div>
                    </div>
                <div id="Lsd" class="form-group hidden">
                              @Html.DropDownListFor(model => model.Lsd, new SelectList(Model.Lsd.data.AsEnumerable(), "idSocGerente", "denominacion"), "por Sociedad Depositaria", new { @class = "form-control" })


                        <div class="se lect_arrow"> </div>
                    </div>
                    <button id="btnFFBuscar" class="btn-blue hidden">BUSCAR</button>
              }
            </div>

        </div>
    </div>
</section>
<script>

    jQuery("#tipoBFF").on('change', function () {
        var opt = jQuery('#tipoBFF').val();
        if (opt == 1) {
            jQuery('#Lti').removeClass("hidden");
            jQuery('#Lsd').removeClass("hidden").addClass("hidden");
            jQuery('#Lsg').removeClass("hidden").addClass("hidden");


        }
        if (opt == 2) {
            jQuery('#Lsg').removeClass("hidden");
            jQuery('#Lsd').removeClass("hidden").addClass("hidden");
            jQuery('#Lti').removeClass("hidden").addClass("hidden");

        }
        if (opt == 3) {
            jQuery('#Lsd').removeClass("hidden");
            jQuery('#Lsg').removeClass("hidden").addClass("hidden");
            jQuery('#Lti').removeClass("hidden").addClass("hidden");

        }
        jQuery('#btnFFBuscar').removeClass("hidden");
    });

</script>

<script type="text/javascript" src="~/Content/assets/js/hechos-relevantes.js"></script>
@Html.Raw(TempData["msg"])

@Html.Partial("_Nav_int_Institucional")
<script type="text/javascript" src="~/Content/assets/js/main.js"></script>